import { NextResponse } from 'next/server';
import { promises as fs } from 'fs';
import path from 'path';

/**
 * Serve the standalone user guide at a clean URL: /guide
 *
 * The guide is a single self-contained HTML file (screenshots embedded as
 * base64) generated by scripts/build-userguide.sh. Next.js only serves files
 * under /public by exact path, so this route maps /guide → public/guide/index.html.
 */
export const dynamic = 'force-static';

export async function GET() {
  try {
    const file = path.join(process.cwd(), 'public', 'guide', 'index.html');
    const html = await fs.readFile(file, 'utf8');
    return new NextResponse(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Cache-Control': 'public, max-age=300',
      },
    });
  } catch {
    return new NextResponse(
      '<!DOCTYPE html><html lang="id"><body style="font-family:system-ui;padding:40px">' +
        '<h1>Panduan belum tersedia</h1>' +
        '<p>Jalankan <code>./scripts/build-userguide.sh</code> untuk menghasilkannya.</p>' +
        '</body></html>',
      { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } }
    );
  }
}
